//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slamby.TAU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slamby.TAU.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add dataset with name: {0}.
        /// </summary>
        internal static string AddDataSetAcceptCommand {
            get {
                return ResourceManager.GetString("AddDataSetAcceptCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save document.
        /// </summary>
        internal static string DocumentDetailsSaveCommand {
            get {
                return ResourceManager.GetString("DocumentDetailsSaveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init data.
        /// </summary>
        internal static string MainLoadCommand {
            get {
                return ResourceManager.GetString("MainLoadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload all data.
        /// </summary>
        internal static string MainRefreshCommand {
            get {
                return ResourceManager.GetString("MainRefreshCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add document button clicked.
        /// </summary>
        internal static string ManageDataDocumentAdd {
            get {
                return ResourceManager.GetString("ManageDataDocumentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tags button clicked.
        /// </summary>
        internal static string ManageDataDocumentAddTag {
            get {
                return ResourceManager.GetString("ManageDataDocumentAddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear tags.
        /// </summary>
        internal static string ManageDataDocumentClearTags {
            get {
                return ResourceManager.GetString("ManageDataDocumentClearTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document copy all to button clicked.
        /// </summary>
        internal static string ManageDataDocumentCopyAllTo {
            get {
                return ResourceManager.GetString("ManageDataDocumentCopyAllTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document copy to button clicked.
        /// </summary>
        internal static string ManageDataDocumentCopyTo {
            get {
                return ResourceManager.GetString("ManageDataDocumentCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify document clicked.
        /// </summary>
        internal static string ManageDataDocumentModify {
            get {
                return ResourceManager.GetString("ManageDataDocumentModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document move all to button clicked.
        /// </summary>
        internal static string ManageDataDocumentMoveAllTo {
            get {
                return ResourceManager.GetString("ManageDataDocumentMoveAllTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document move to button clicked.
        /// </summary>
        internal static string ManageDataDocumentMoveTo {
            get {
                return ResourceManager.GetString("ManageDataDocumentMoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove document.
        /// </summary>
        internal static string ManageDataDocumentRemove {
            get {
                return ResourceManager.GetString("ManageDataDocumentRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassign tags button clicked.
        /// </summary>
        internal static string ManageDataDocumentRemoveTags {
            get {
                return ResourceManager.GetString("ManageDataDocumentRemoveTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filter button clicked.
        /// </summary>
        internal static string ManageDataFilterApply {
            get {
                return ResourceManager.GetString("ManageDataFilterApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tags for filter button clicked.
        /// </summary>
        internal static string ManageDataFilterTagSelect {
            get {
                return ResourceManager.GetString("ManageDataFilterTagSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading documents.
        /// </summary>
        internal static string ManageDataLoadDocuments {
            get {
                return ResourceManager.GetString("ManageDataLoadDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading tags.
        /// </summary>
        internal static string ManageDataLoadTags {
            get {
                return ResourceManager.GetString("ManageDataLoadTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get sample button clicked.
        /// </summary>
        internal static string ManageDataSampleGet {
            get {
                return ResourceManager.GetString("ManageDataSampleGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tags for sample button clicked.
        /// </summary>
        internal static string ManageDataSampleTagSelect {
            get {
                return ResourceManager.GetString("ManageDataSampleTagSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add dataset button clicked.
        /// </summary>
        internal static string ManageDataSetAddCommand {
            get {
                return ResourceManager.GetString("ManageDataSetAddCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete dataset.
        /// </summary>
        internal static string ManageDataSetDeleteCommand {
            get {
                return ResourceManager.GetString("ManageDataSetDeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag button clicked.
        /// </summary>
        internal static string ManageDataTagAdd {
            get {
                return ResourceManager.GetString("ManageDataTagAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export words button clicked.
        /// </summary>
        internal static string ManageDataTagExportWords {
            get {
                return ResourceManager.GetString("ManageDataTagExportWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify tag button clicked.
        /// </summary>
        internal static string ManageDataTagModify {
            get {
                return ResourceManager.GetString("ManageDataTagModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tag.
        /// </summary>
        internal static string ManageDataTagRemove {
            get {
                return ResourceManager.GetString("ManageDataTagRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading processes.
        /// </summary>
        internal static string ManageProcessLoadProcesses {
            get {
                return ResourceManager.GetString("ManageProcessLoadProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create service button clicked.
        /// </summary>
        internal static string ManageServiceCreate {
            get {
                return ResourceManager.GetString("ManageServiceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete service button clicked.
        /// </summary>
        internal static string ManageServiceDelete {
            get {
                return ResourceManager.GetString("ManageServiceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify service button clicked.
        /// </summary>
        internal static string ManageServiceModify {
            get {
                return ResourceManager.GetString("ManageServiceModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Service Details button clicked.
        /// </summary>
        internal static string ManageServiceShowDetails {
            get {
                return ResourceManager.GetString("ManageServiceShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpreationCancelled.
        /// </summary>
        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set endpoint.
        /// </summary>
        internal static string SettingsApplyEndpointCommand {
            get {
                return ResourceManager.GetString("SettingsApplyEndpointCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cancelled..
        /// </summary>
        internal static string StatusDialogCancel {
            get {
                return ResourceManager.GetString("StatusDialogCancel", resourceCulture);
            }
        }
    }
}
